# Generated by Django 5.0.3 on 2024-04-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_studentuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='type',
            field=models.CharField(blank=True, choices=[('cust_user', 'User'), ('recruiter', 'Recruiter')], max_length=10, null=True),
        ),
    ]
