# Generated by Django 5.0.3 on 2024-04-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_studentuser_resume_alter_studentuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
