# Generated by Django 5.0.3 on 2024-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_studentuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
