# Generated by Django 5.0.3 on 2024-04-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
