# Generated by Django 5.0.3 on 2024-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_recruiter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
