# Generated by Django 5.0.3 on 2024-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_eligibility_criteria_job_job_type_job_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role_responsibilities',
            field=models.CharField(default='Software developer, Designing, coding, testing, and debugging software applications', max_length=500),
        ),
    ]
