# Generated by Django 5.0.3 on 2024-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_role_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='about_company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
