# Generated by Django 5.0.3 on 2024-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_recruiter_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mode_of_work',
            field=models.CharField(default='on-site', max_length=10),
        ),
    ]
