# Generated by Django 5.0.3 on 2024-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
