# Generated by Django 5.0.3 on 2024-05-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_studentuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
