# Generated by Django 5.0.3 on 2024-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_alter_recruiter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
